$(document).ready(function () {
    $("#prox").click(function () {
        $(".d1").addClass("d6");
        $(".d6").removeClass("d1");
        $(".d2").addClass("d1");
        $(".d1").removeClass("d2");
        $(".d3").addClass("d2");
        $(".d2").removeClass("d3");
        $(".d4").addClass("d3");
        $(".d3").removeClass("d4");
        $(".d5").addClass("d4");
        $(".d4").removeClass("d5");
        $(".d6").addClass("d5");
        $(".d5").removeClass("d6");
    });

    $("#prev").click(function () {
        $(".d5").addClass("d6");
        $(".d6").removeClass("d5");
        $(".d4").addClass("d5");
        $(".d5").removeClass("d4");
        $(".d3").addClass("d4");
        $(".d4").removeClass("d3");
        $(".d2").addClass("d3");
        $(".d3").removeClass("d2");
        $(".d1").addClass("d2");
        $(".d2").removeClass("d1");
        $(".d6").addClass("d1");
        $(".d1").removeClass("d6");

    });
 
    $(".c1").click(function () {
        $("#header").addClass("header_C1");
        $("#header").removeClass("header_C2");
        $("#header").removeClass("header_C3");
        $("#header").removeClass("header_C4");
        $("#header").removeClass("header_C5");
        $("#header").removeClass("header_C6");
        $(".cimg1").addClass("cActive");
        $(".cimg2").removeClass("cActive");
        $(".cimg3").removeClass("cActive");
        $(".cimg4").removeClass("cActive");
        $(".cimg5").removeClass("cActive");
        $(".cimg6").removeClass("cActive");
    });

    $(".c2").click(function () {
        $("#header").addClass("header_C2");
        $("#header").removeClass("header_C1");
        $("#header").removeClass("header_C3");
        $("#header").removeClass("header_C4");
        $("#header").removeClass("header_C5");
        $("#header").removeClass("header_C6");
        $(".cimg2").addClass("cActive");
        $(".cimg1").removeClass("cActive");
        $(".cimg3").removeClass("cActive");
        $(".cimg4").removeClass("cActive");
        $(".cimg5").removeClass("cActive");
        $(".cimg6").removeClass("cActive");
    });

    $(".c3").click(function () {
        $("#header").addClass("header_C3");
        $("#header").removeClass("header_C2");
        $("#header").removeClass("header_C1");
        $("#header").removeClass("header_C4");
        $("#header").removeClass("header_C5");
        $("#header").removeClass("header_C6");
        $(".cimg3").addClass("cActive");
        $(".cimg2").removeClass("cActive");
        $(".cimg1").removeClass("cActive");
        $(".cimg4").removeClass("cActive");
        $(".cimg5").removeClass("cActive");
        $(".cimg6").removeClass("cActive");
    });

    $(".c4").click(function () {
        $("#header").addClass("header_C4");
        $("#header").removeClass("header_C2");
        $("#header").removeClass("header_C3");
        $("#header").removeClass("header_C1");
        $("#header").removeClass("header_C5");
        $("#header").removeClass("header_C6");
        $(".cimg4").addClass("cActive");
        $(".cimg2").removeClass("cActive");
        $(".cimg3").removeClass("cActive");
        $(".cimg1").removeClass("cActive");
        $(".cimg5").removeClass("cActive");
        $(".cimg6").removeClass("cActive");
    });

    $(".c5").click(function () {
        $("#header").addClass("header_C5");
        $("#header").removeClass("header_C2");
        $("#header").removeClass("header_C3");
        $("#header").removeClass("header_C4");
        $("#header").removeClass("header_C1");
        $("#header").removeClass("header_C6");
        $(".cimg5").addClass("cActive");
        $(".cimg2").removeClass("cActive");
        $(".cimg3").removeClass("cActive");
        $(".cimg4").removeClass("cActive");
        $(".cimg1").removeClass("cActive");
        $(".cimg6").removeClass("cActive");
    });

    $(".c6").click(function () {
        $("#header").addClass("header_C6");
        $("#header").removeClass("header_C2");
        $("#header").removeClass("header_C3");
        $("#header").removeClass("header_C4");
        $("#header").removeClass("header_C5");
        $("#header").removeClass("header_C1");
        $(".cimg6").addClass("cActive");
        $(".cimg2").removeClass("cActive");
        $(".cimg3").removeClass("cActive");
        $(".cimg4").removeClass("cActive");
        $(".cimg5").removeClass("cActive");
        $(".cimg1").removeClass("cActive");
    });

    $("#prox").click(function () {
        if (projectTextsActual == 4) {
            projectTextsActual = 0;
        } else {
            projectTextsActual = projectTextsActual + 1;
        }
        $('#programDescription').animate({ marginLeft: "-500px", opacity: 0 }, 350, 'swing', function () {
            $('#programDescription > h2').text(projectTitleTexts[projectTextsActual]);
            $('#programDescription > p').text(projectTexts[projectTextsActual]);
            $('#programDescription').css('margin-left', 'auto');
            $('#programDescription').css('margin-right', '-500px');
            $('#programDescription').animate({
                marginRight: "500px",
                opacity: 1
            }, 350, 'swing', function () {
                $('#programDescription').css('margin-right', 'auto');
            });
        });
    })

    $("#prev").click(function () {

        if (projectTextsActual == 0) {
            projectTextsActual = 4;
        } else {
            projectTextsActual = projectTextsActual - 1;
        }
        $('#programDescription').animate({ marginRight: "-500px", opacity: 0 }, 350, 'swing', function () {
            $('#programDescription > h2').text(projectTitleTexts[projectTextsActual]);
            $('#programDescription > p').text(projectTexts[projectTextsActual]);
            $('#programDescription').css('margin-right', 'auto');
            $('#programDescription').css('margin-left', '-500px');

            $('#programDescription').animate({
                marginLeft: "500px",
                opacity: 1
            }, 350, 'swing', function () {
                $('#programDescription').css('margin-left', 'auto');
            });
        });
    });

    $("#java1").click(function () {
        $(".showprogramjava1").show();
        $(".showchatjava1").show();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java1").addClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java2").click(function () {
        $(".showprogramjava2").show();
        $(".showchatjava2").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java2").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java3").click(function () {
        $(".showprogramjava3").show();
        $(".showchatjava3").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java3").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java4").click(function () {
        $(".showprogramjava4").show();
        $(".showchatjava4").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java4").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java5").click(function () {
        $(".showprogramjava5").show();
        $(".showchatjava5").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java5").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java6").click(function () {
        $(".showprogramjava6").show();
        $(".showchatjava6").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java6").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java7").click(function () {
        $(".showprogramjava7").show();
        $(".showchatjava7").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java7").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java8").click(function () {
        $(".showprogramjava8").show();
        $(".showchatjava8").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $(".showprogramjava9").hide();
        $(".showchatjava9").hide();
        $("#java8").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
        $("#java9").removeClass("liActivejf");
    });
    $("#java9").click(function () {
        $(".showprogramjava9").show();
        $(".showchatjava9").show();
        $(".showprogramjava1").hide();
        $(".showchatjava1").hide();
        $(".showprogramjava2").hide();
        $(".showchatjava2").hide();
        $(".showprogramjava3").hide();
        $(".showchatjava3").hide();
        $(".showprogramjava5").hide();
        $(".showchatjava5").hide();
        $(".showprogramjava6").hide();
        $(".showchatjava6").hide();
        $(".showprogramjava7").hide();
        $(".showchatjava7").hide();
        $(".showprogramjava8").hide();
        $(".showchatjava8").hide();
        $(".showprogramjava4").hide();
        $(".showchatjava4").hide();
        $("#java9").addClass("liActivejf");
        $("#java1").removeClass("liActivejf");
        $("#java2").removeClass("liActivejf");
        $("#java3").removeClass("liActivejf");
        $("#java5").removeClass("liActivejf");
        $("#java6").removeClass("liActivejf");
        $("#java7").removeClass("liActivejf");
        $("#java8").removeClass("liActivejf");
        $("#java4").removeClass("liActivejf");
    });

    $("#front1").click(function () {
        $(".showprogramfront1").show();
        $(".showchatfront1").show();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front1").addClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front2").click(function () {
        $(".showprogramfront2").show();
        $(".showchatfront2").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front2").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });

    $("#front3").click(function () {
        $(".showprogramfront3").show();
        $(".showchatfront3").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front3").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });

    $("#front4").click(function () {
        $(".showprogramfront4").show();
        $(".showchatfront4").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front4").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front5").click(function () {
        $(".showprogramfront5").show();
        $(".showchatfront5").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front5").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front6").click(function () {
        $(".showprogramfront6").show();
        $(".showchatfront6").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front6").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front7").click(function () {
        $(".showprogramfront7").show();
        $(".showchatfront7").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front7").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front8").click(function () {
        $(".showprogramfront8").show();
        $(".showchatfront8").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $(".showprogramfront9").hide();
        $(".showchatfront9").hide();
        $("#front8").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
        $("#front9").removeClass("liActivejf");
    });
    $("#front9").click(function () {
        $(".showprogramfront9").show();
        $(".showchatfront9").show();
        $(".showprogramfront1").hide();
        $(".showchatfront1").hide();
        $(".showprogramfront2").hide();
        $(".showchatfront2").hide();
        $(".showprogramfront3").hide();
        $(".showchatfront3").hide();
        $(".showprogramfront5").hide();
        $(".showchatfront5").hide();
        $(".showprogramfront6").hide();
        $(".showchatfront6").hide();
        $(".showprogramfront7").hide();
        $(".showchatfront7").hide();
        $(".showprogramfront8").hide();
        $(".showchatfront8").hide();
        $(".showprogramfront4").hide();
        $(".showchatfront4").hide();
        $("#front9").addClass("liActivejf");
        $("#front1").removeClass("liActivejf");
        $("#front2").removeClass("liActivejf");
        $("#front3").removeClass("liActivejf");
        $("#front5").removeClass("liActivejf");
        $("#front6").removeClass("liActivejf");
        $("#front7").removeClass("liActivejf");
        $("#front8").removeClass("liActivejf");
        $("#front4").removeClass("liActivejf");
    });
});